
#
# ===================================================================
# 分布式文件系统Minio配置 minio
# ===================================================================



minio:
  url: http://8.131.61.233:8080 #Minio服务所在地址
  bucketName: "apps" #存储桶名称
  accessKey: "@jianDan111" #访问的key
  secretKey: "@jianDan111" #访问的秘钥