
#
# ===================================================================
# 分布式文件系统Minio配置 minio
# ===================================================================



minio:
  url: http://21.22.12.121:8080 #Minio服务所在地址
  bucketName: "apps" #存储桶名称
  accessKey: "111111" #访问的key
  secretKey: "111111" #访问的秘钥